#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
polybar &


bspc monitor -d α β γ δ ε 

bspc config border_width         2
bspc config window_gap          15
bspc config top_padding		10
bspc config bottom_padding	10
bspc config left_padding	10
bspc config right_padding	10

bspc config normal_border_color         "#050505"
bspc config active_border_color         "#050505"
bspc config focused_border_color        "#efefef"
bspc config presel_feedback_color       "#d5a4b5"
bspc config urgent_border_color         "#d5a4b5"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

